-- 补充 market_data 表缺失的列
-- 使用 IF NOT EXISTS 保证幂等，可重复执行

ALTER TABLE market_data
  ADD COLUMN IF NOT EXISTS ask DECIMAL(18, 6),
  ADD COLUMN IF NOT EXISTS bid DECIMAL(18, 6),
  ADD COLUMN IF NOT EXISTS price_gram_24k DECIMAL(18, 6),
  ADD COLUMN IF NOT EXISTS open_price DECIMAL(18, 6) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS prev_close_price DECIMAL(18, 6) NOT NULL DEFAULT 0;
